name: Mirror TUF targets
description: Used to mirror TUF targets from a source to a destination
inputs:
  metadata:
    description: source metadata location
    default: https://docker.github.io/tuf/metadata
    required: true
  source:
    description: source targets location
    default: https://docker.github.io/tuf/targets
    required: true
  destination:
    description: destination targets location
    required: true
    default: docker://docker/tuf-targets
  tuf-root:
    description: embedded TUF root (dev, staging, or prod)
    default: "prod"
  flags:
    description: flags to pass to the go-tuf-mirror command
    required: false
    default: ""
runs:
  using: docker
  image: docker://docker/go-tuf-mirror@sha256:d4fb86ee5c94150be7adbcf6e82004f9baafe740de3c40b6e77d58bd639b5dfb # v0.1.9
  args:
    - targets
    - ${{ inputs.flags }}
    - --metadata=${{ inputs.metadata }}
    - --source=${{ inputs.source }}
    - --destination=${{ inputs.destination }}
    - --tuf-root=${{ inputs.tuf-root }}
  env:
    DOCKER_CONFIG: /github/workspace/.docker
